# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
FastAPI application for the Supply Chain RL Environment.

Exposes HTTP and WebSocket endpoints compatible with EnvClient.

Endpoints:
    POST /reset    — Reset the environment, returns initial observation
    POST /step     — Execute a routing action, returns next observation + reward
    GET  /state    — Get current episode state
    GET  /schema   — Get action / observation JSON schemas
    WS   /ws       — WebSocket for persistent low-latency sessions
    GET  /web      — Interactive web UI (auto-generated by openenv)
    GET  /health   — Health check for container orchestration

Usage:
    # Development
    uvicorn server.app:app --reload --host 0.0.0.0 --port 8000

    # Production
    uvicorn server.app:app --host 0.0.0.0 --port 8000 --workers 4
"""

try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:
    raise ImportError(
        "openenv-core is required. Install with:\n    uv sync"
    ) from e

import sys, os
# Ensure both repo root and server/ dir are on the path regardless of how
# the process was launched (uvicorn, docker, direct python, etc.)
_repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
_server_dir = os.path.dirname(os.path.abspath(__file__))
for _p in [_repo_root, _server_dir]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

try:
    from supply_chain.models import SupplyChainAction, SupplyChainObservation
except ImportError:
    from models import SupplyChainAction, SupplyChainObservation  # type: ignore

from supply_chain_environment import SupplyChainEnvironment  # always on path via sys.path above


app = create_app(
    SupplyChainEnvironment,          # pass class for factory mode
    SupplyChainAction,
    SupplyChainObservation,
    env_name="supply_chain",
    max_concurrent_envs=4,           # support 4 parallel RL workers
)


def main(host: str = "0.0.0.0", port: int = 8000):
    """Entry point for direct execution."""
    import uvicorn
    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    main(port=args.port)
